version: "3"

services:
  nginx-ui:
    image: registry.cn-hangzhou.aliyuncs.com/tuon-pub/nginx-ui
    restart: always
    container_name: nginx-ui
    ports:
      - 8080:8080
    volumes:
      - ./data:/app/data
